{"name": "test_check_succes_profile_telegram", "status": "failed", "statusDetails": {"message": "AssertionError: Неверный код ответа, получен 404\nassert 404 == 200\n +  where 404 = <Response [404]>.status_code", "trace": "@allure.feature(\"Проверка подтверждения телеграмм профиля\")\n    def test_check_succes_profile_telegram(): #Проверка подтверждения телеграмм профиля\n        \"\"\"\n             Проверка подтверждения телеграмм профиля\n        \"\"\"\n        response = requests.get(utils.urlTelegramMe, headers=utils.header)\n        with allure.step(f'Status code {response.status_code}'):\n>           assert response.status_code == 200, f\"Неверный код ответа, получен {response.status_code}\"\nE           AssertionError: Неверный код ответа, получен 404\nE           assert 404 == 200\nE            +  where 404 = <Response [404]>.status_code\n\nmain.py:1046: AssertionError"}, "description": "\n         Проверка подтверждения телеграмм профиля\n    ", "steps": [{"name": "Status code 404", "status": "failed", "statusDetails": {"message": "AssertionError: Неверный код ответа, получен 404\nassert 404 == 200\n +  where 404 = <Response [404]>.status_code\n", "trace": "  File \"C:\\Users\\baranchikov.k\\PycharmProjects\\APITEST\\main.py\", line 1046, in test_check_succes_profile_telegram\n    assert response.status_code == 200, f\"Неверный код ответа, получен {response.status_code}\"\n"}, "start": 1652781541758, "stop": 1652781541759}], "start": 1652781541600, "stop": 1652781541773, "uuid": "581500be-8eb2-4a2c-bba9-6b6c770c358a", "historyId": "b8b0addb158d0d4671e56e61d42a3018", "testCaseId": "14342ad4ea82e7ffe7c0e78ed46b283e", "fullName": "main#test_check_succes_profile_telegram", "labels": [{"name": "feature", "value": "Проверка подтверждения телеграмм профиля"}, {"name": "suite", "value": "main"}, {"name": "host", "value": "ru47-devgen-16"}, {"name": "thread", "value": "11268-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "main"}]}